### PR TITLE
Updating SVGViewSpec to be tagged a Protocol

### PR DESCRIPTION
**Pull request by hartra344**
This allows the library to be built for physical devices

### CODE REVIEW

**Comment by sushihangover** [comment]
>This allows the library to be built for physical devices

Not sure I understand that comment...

So you are subclassing `SVGViewSpec` and need to override some of the default getters?

**Comment by hartra344** [comment]
I receive the following error when building for a physical device(Simulator is unaffected):

Error MT5211: Native linking failed, undefined Objective-C class: SVGViewSpec. The symbol '_OBJC_CLASS_$_SVGViewSpec' could not be found in any of the libraries or frameworks linked with your application. (MT5211)

Research on the error brought up this: https://forums.xamarin.com/discussion/16489/new-type-registrar-in-xamarin-ios-7-2-1-errors-mt5210-and-mt5211 

Tried this from the link and it worked perfectly:
To fix the problem, you'll need to add the [Protocol] attribute (as requested by the error message), and then recompile the binding library. If you don't have access to the source for the binding library, the author of the library will have to perform this step.

**Comment by hyldmo** [comment]
I am getting the samme error as well, with the proposed fix working too

**Comment by sushihangover** [comment]
@hartra344  @eivhyl  Thanks for the info everyone, it is strange as I did this binding for someone that is using it for a card game that is live in the App Store and have had no issues building `.ipa`s... 

I published a new Nuget and have created a `.ipa` from it but would love it if you could test it also.

Thanks again.

https://www.nuget.org/packages/SushiHangover.SVGKit.Binding/1.0.3

**Comment by hyldmo** [comment]
The nuget package works great for me at least. Tested against iPhone 5c. Thank you!

**Pull request merged**
